### ISSUE TITLE
setup with backstage and github - node create-gh-app/index.js. issue

### ISSUE THREAD

**Issue by gcp-innovate** [humanitec-architecture/reference-architecture-gcp#17]
I am trying to setup with backstage and github. As pre-requisite package creation fails. Is there some dependency that i need to check 
sudo node create-gh-app/index.js.                                                                                                                                                           
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/randd_gcp1/reference-architecture-gcp/examples/with-backstage/create-gh-app/index.js.'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

**Comment by johanneswuerbach** [comment]
Hey, the script shouldn't need any additional dependencies. Could you tell me which node version you are using `node -v`?

**Comment by gcp-innovate** [comment]
v21.6.1

**Comment by johanneswuerbach** [comment]
In the first error you have an additional `.` in `node create-gh-app/index.js.`, the command should be `node create-gh-app/index.js` (without the `.` at the end). Could you try to run node without sudo?

I just checked and for me both node versions work, odd 🤔.

**Comment by gcp-innovate** [comment]
it runs actually but stuck at port 3000 at 127.0.0.1. 
node reference-architecture-gcp/examples/with-backstage/create-gh-app/index.js
Open http://127.0.0.1:3000

I tried running terraform plan but it gives below message. Will node create-gh-app/index.js create the json files as well or this needs to be placed.

 sudo terraform plan                                                                                                                                                                         
╷
│ Error: Invalid function argument
│ 
│   on backstage-github.tf line 5, in locals:
│    5:   github_app_credentials      = jsondecode(file("${path.module}/${local.github_app_credentials_file}"))
│     ├────────────────
│     │ while calling file(path)
│     │ local.github_app_credentials_file is "github-app-credentials.json"
│     │ path.module is "."
│ 
│ Invalid value for "path" parameter: no file exists at "./github-app-credentials.json"; this function works only with files that are distributed as part of the configuration source code, so if this file will be created by a resource in this configuration you
│ must instead obtain this result from an attribute of that resource.
╵

**Comment by johanneswuerbach** [comment]
Starting is good 🎉 , once the "Open http://127.0.0.1:3000/" output is displayed you need to open http://127.0.0.1:3000/ in your browser to generate the respective credentials file, which will afterwards be used by the terraform plan.

**Comment by gcp-innovate** [comment]
Ok...i had to install the ubuntu desktop and access url via browser and it installed the app on selected repository.  App got installed. json got created. 

Terraform plan is failing with backstage..However, i am using environment variable for service user for humanitec.

Plan: 32 to add, 0 to change, 0 to destroy.
╷
│ Error: Missing API Token Configuration
│ 
│   with provider["registry.terraform.io/humanitec/humanitec"],
│   on provider.tf line 23, in provider "humanitec":
│   23: provider "humanitec" {
│ 
│ While configuring the provider, the API token was not found in the HUMANITEC_TOKEN environment variable or provider configuration block token attribute.
╵
╷
│ Error: Unable to create Humanitec client
│ 
│   with provider["registry.terraform.io/humanitec/humanitec"],
│   on provider.tf line 23, in provider "humanitec":
│   23: provider "humanitec" {
│ 
│ empty token

**Comment by gcp-innovate** [comment]
> Do you have the `HUMANITEC_TOKEN` environment variable configured?

yes.

**Comment by johanneswuerbach** [comment]
You usually get this error message when the Github Token you are using doesn't have enough permissions, could you check that the token has all the scopes listed here https://github.com/humanitec-architecture/reference-architecture-gcp/tree/main/examples/with-backstage#prerequisites?

**Comment by gcp-innovate** [comment]
> You usually get this error message when the Github Token you are using doesn't have enough permissions, could you check that the token has all the scopes listed here https://github.com/humanitec-architecture/reference-architecture-gcp/tree/main/examples/with-backstage#prerequisites?

Have all the permissions on the PAT. Still not sure why the issue is coming up

**Comment by johanneswuerbach** [comment]
Sorry for the delay, the PAT needs to be a personal token, which can be generated here https://github.com/settings/tokens.

Did you made the correct export? You should be able to run `echo $GITHUB_TOKEN` and `echo $GITHUB_ORG_ID` and see the correct values (please don't share them here as they are secrets).

**Comment by johanneswuerbach** [comment]
Closing this due to inactive, if this is still a concern, please re-open this issue. Thank you 👍

**Comment by gcp-innovate** [comment]
Deployment was successful. However, the github action fails at 

Run humctl score deploy

 CONTAINER_REGISTRY: us-east4-docker.pkg.dev/idp-humanitec/htc-ref-arch
    TAG: d041720
normalizeScoreSpec .
Unexpected error occurred.
failed to normalize score spec: failed to map score file: 1 error(s) decoding:

* 'containers[backstage].files[0].content' expected type 'string', got unconvertible type '[]interface {}', value: '[# Name: Backstage-Humanitec
appId: ${values.GITHUB_APP_ID}
webhookUrl: https://${externals.dns.host}
clientId: ${values.GITHUB_APP_CLIENT_ID}
clientSecret: ${values.GITHUB_APP_CLIENT_SECRET}
webhookSecret: ${values.GITHUB_APP_WEBHOOK_SECRET}
privateKey: |
  ${values.GITHUB_APP_PRIVATE_KEY}
]'
Error: Process completed with exit code 22.

**Comment by mathieu-benoit** [comment]
@gcp-innovate , I'm able to reproduce the issue with `humctl score deploy`, we'll keep you posted as soon as it's fixed. Thanks!

**Comment by gcp-innovate** [comment]
ok. i shall wait

**Comment by mathieu-benoit** [comment]
@gcp-innovate, this error is now fixed thanks to this PR: https://github.com/humanitec-architecture/backstage/pull/20, you can `git pull` this repo `humanitec-architecture/backstage` again, and the deployment of `backstage` should now work.

**Comment by gcp-innovate** [comment]
Thanks, able to deploy  with backstage
